# Codecov configuration for Factompiler

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 75%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "**/__pycache__/**/*"
  - "venv/**/*"
  - ".venv/**/*"
  - "temp/**/*"
  - "output/**/*"
  - "factorio-draftsman/**/*"
  - "**/__init__.py"

github_checks:
  annotations: true
